### ISSUE TITLE
Big endian support for DAT

### ISSUE THREAD

**Issue by Timo654** [cabalex/astral-extractor#1]
Hi,

It would be nice if it were possible to switch the endian for the DAT. This would allow Metal Gear Rising Revengeance PS3/X360 and Bayonetta 2 Wii U dat files to be extracted with the tool.

There shouldn't be any differences between the dat formats in the games other than some padding, so theoretically it should work. The tool can load MGR PC and Bayonetta 2 Switch files already (they're little endian).
Here are some big endian files that you can test:
[examples.zip](https://github.com/cabalex/astral-extractor/files/8017714/examples.zip)

**Comment by cabalex** [comment]
Hey there, thanks for your issue!
The tool isn't explicitly designed for use in other Platinum games (although that might be worth expanding into the future), but big endian support is pretty easy to implement. However, currently I'm working on a v1.0.0 overhaul of the entire extractor that should bring about major improvements to the app as a whole. As such, I'm moving away from development on v0.X.X (as it's pretty terrible code and not fun to work around).

I've already implemented it [on the v1 development branch](https://github.com/cabalex/astral-extractor/tree/v1) (not being hosted on GitHub Pages right now, so you'll have to clone the branch and run it in [a local web server](https://marketplace.visualstudio.com/items?itemName=yandeu.five-server)); however, I don't have any plans to retrofit the old extractor at the moment. I'll update you when it's fully up to par with the feature set of v0.
Thanks for your understanding!

![image](https://user-images.githubusercontent.com/31020729/152960983-4a1fbc1e-0fc7-4296-aa63-e8f3d7bbed61.png)

As a side question, I'm a bit curious: is it only the .DAT files that change endianness? I'm not sure if I need to implement deeper changes.

**Comment by Timo654** [comment]
No, all files change endian.

I don't have Astral Chain, so I can't compare how the file formats are compared to that, but wtb/wta/wtp files are mostly the same between games (except some funny things like bayo2 wiiu storing the texture headers in wta)
Uvd and uid seemed same content wise between MGR and Bayo2 so maybe it's the same with AC.
BXM might be same endian everywhere, not sure.

Basically, all formats should have changed endian, the only one I've seen so far that actually had a different magic is wta/wtb (wtp is data).

Also, thanks for the tool. I was just curious what other Platinum games formats had been documented and found this.

**Comment by cabalex** [comment]
It's... been quite literally a year, but I finally got around to implementing this in a public release! (sorry, it went through development hell... and I switched frameworks...)
It's a new tool, and you can visit it here: https://cabalex.github.io/platinum-extractor/
I'm still working on file support, but it appears that *every byte* in each file swaps endian. You should be able to extract and download the proper files with the tool.

Hopefully it works for you!

![image](https://user-images.githubusercontent.com/31020729/218265798-bc276f9d-5b78-4541-b4c8-b028726c2d55.png)
